apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soa
spec:
  ingressClassName: nginx
  rules:
    - host: "soa.prj-1774812044584338805.158.160.236.21.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soa
                port:
                  number: 80
