apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw1-api
spec:
  ingressClassName: nginx
  rules:
    - host: "hw1-api.prj-1774800094094665788.158.160.241.48.sslip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hw1-api
                port:
                  number: 80
