apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-api
spec:
  ingressClassName: nginx
  rules:
    - host: "test-api.346a6e41-6b8a-4d2f-b638-3e93ee87f46c.158.160.241.48.sslip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-api
                port:
                  number: 80
