apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-cinema
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: cinema
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    editable: true
