apiVersion: apps/v1
kind: Deployment
metadata:
  name: soa
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soa
  template:
    metadata:
      labels:
        app: soa
    spec:
      containers:
        - name: soa
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 7981
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 7981
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7981
            initialDelaySeconds: 20
            periodSeconds: 15
