apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soa
spec:
  ingressClassName: nginx
  rules:
    - host: "prj-1774641263248340551.158.160.238.148.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soa
                port:
                  number: 80
