"""initial

Revision ID: 3f8a1c2e9d47
Revises:
Create Date: 2026-03-16 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8a1c2e9d47"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flights",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flight_number", sa.String(length=10), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("available_seats", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "DEPARTED",
                "CANCELLED",
                "COMPLETED",
                name="flight_status_enum",
            ),
            server_default="SCHEDULED",
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_seats >= 0", name="ck_flights_available_seats_non_negative"
        ),
        sa.CheckConstraint(
            "available_seats <= total_seats", name="ck_flights_available_seats_not_exceed_total"
        ),
        sa.CheckConstraint("price > 0", name="ck_flights_price_positive"),
        sa.CheckConstraint("total_seats > 0", name="ck_flights_total_seats_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flight_number", "departure_time", name="uq_flights_number_departure"),
    )
    op.create_table(
        "seat_reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flight_id", sa.BigInteger(), nullable=False),
        sa.Column("booking_id", sa.String(length=36), nullable=False),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RELEASED", "EXPIRED", name="reservation_status_enum"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "seat_count > 0", name="ck_seat_reservations_seat_count_positive"
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id", name="uq_seat_reservations_booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seat_reservations")
    op.drop_table("flights")
    sa.Enum(name="reservation_status_enum").drop(op.get_bind())
    sa.Enum(name="flight_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
